# Generated by Django 3.2.5 on 2021-10-16 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_auto_20211016_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcaserelevance',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='taskcaserelevance',
            old_name='task_id',
            new_name='task',
        ),
    ]
